import axios from "axios";
import Head from "next/head";
import Image from "next/image";
import Home from "./home"
import Footer from "pages/component/layout/Footer";
import Header from "pages/component/layout/Header";
import Input from "pages/component/form/Input";

export default function Index({ categoryList, productList }) {
  return (
    <div className="">
    <Head>
      <title>Eataway</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
   
   
    <Home categoryList={categoryList} productList={productList} />
    </div>
  );
}

export const getServerSideProps = async () => {
  const res = await axios.get(`${process.env.NEXT_PUBLIC_API_URL}/categories`);
  const product = await axios.get(
    `${process.env.NEXT_PUBLIC_API_URL}/products`
  );
  return {
    props: {
      categoryList: res.data ? res.data : [],
      productList: product.data ? product.data : [],
    },
  };
};